package com.zone24x7.ibrac.recengine.pipeline.flatrecpipeline.handlers;

import com.zone24x7.ibrac.recengine.enumeration.RecommendationType;
import com.zone24x7.ibrac.recengine.pojo.*;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import java.util.Collections;

@Component
@Qualifier("accumulationHandler")
public class AccumulationHandler implements RecUnitHandler {

    /**
     * Handles the accumulation of the results generated by multiple handlers.
     *
     * @param recInputParams  the input parameters for recommendation generation
     * @param recStatusParams rec status parameters for recommendation generation
     * @param activeBundle    the activeBundle for recommendation generation
     */
    @Override
    public void handleTask(RecInputParams recInputParams, RecStatusParams recStatusParams, ActiveBundle activeBundle) {
        createRecResult(recInputParams, recStatusParams, activeBundle);
    }

    /**
     * Creates the recResult object based on the RecStatusParams and sets to status params
     *
     * @param recInputParams  input params carrying object
     * @param recStatusParams status carrying object
     * @param activeBundle    active bundle details object
     */
    private static void createRecResult(RecInputParams recInputParams, RecStatusParams recStatusParams, ActiveBundle activeBundle) {
        RecResult<FlatRecPayload> recPayloadRecResult = new RecResult<>();
        recPayloadRecResult.setPlaceHolder(recInputParams.getPlaceholder());
        recPayloadRecResult.setRecCycleStatus(recStatusParams.getRecCycleStatus());

        //Populate payload
        MultipleAlgorithmResult multipleAlgorithmResult = recStatusParams.getMultipleAlgorithmResult();
        FlatRecPayload flatRecPayload = new FlatRecPayload();
        if (multipleAlgorithmResult != null) {
            flatRecPayload.setProducts(multipleAlgorithmResult.getRecProducts());
            flatRecPayload.setDisplayText(multipleAlgorithmResult.getDisplayText());
        }

        recPayloadRecResult.setRecPayload(flatRecPayload);

        //Populate meta info
        RecMetaInfo recMetaInfo = new RecMetaInfo();
        if (multipleAlgorithmResult != null) {
            recMetaInfo.setAlgoToProductsMap(multipleAlgorithmResult.getAlgoToProductsMap());
            recMetaInfo.setAlgoToUsedCcp(multipleAlgorithmResult.getAlgoToUsedCcp());
            recMetaInfo.setBundleId(activeBundle.getId());
            recMetaInfo.setType(RecommendationType.FLAT_RECOMMENDATION);
            recMetaInfo.setLimitToApply(activeBundle.getLimitToApply());
        }

        //TODO: add executed rule set once completed
        recMetaInfo.setExecutedFilteringRuleInfoList(Collections.emptySet());

        recPayloadRecResult.setRecMetaInfo(recMetaInfo);


        //Set to status params
        recStatusParams.setRecResult(recPayloadRecResult);
    }
}